### PR TITLE
added tags functionality 

### PR DESCRIPTION
**Pull request by weljoda**
Hi I added the possibility to manage tags. It would be nice to add this to the main repository.

### CODE REVIEW

**Comment by gscriver** [comment]
The tags need to be added to Member.toString(), MailChimpList.addMember() and MailChimpList.updateMember() methods.

**Comment by gscriver** [comment]
Oops, scratch MailChimpList.addMember() from my previous comment since that is a minimal create function.

**Comment by gscriver** [comment]
Ok, as I dig a little deeper I see that tags are read only members for the PUT/PATCH/POST methods for members so you can disregard my prior comments.

**Comment by weljoda** [comment]
Thanks gscriver for your review. The mailchimp API handles tags a bit different than other member values. In my implementation you have to add or remove tags on the member first. In a second step it is necessary to triger the updateTags method, that finally persists the changes.
If you are thinking about an other implementation I'm open to any changes. Right now it works quite well for my usecase.

**Pull request merged**
